---

- name: make my source directory
  file:
    path: "{{ my_git_repo_root }}"
    state: directory

- name: git clone dotfiles
  git:
    repo: "https://github.com/jiro4989/dotfiles"
    dest: "{{ my_git_repo_root }}/dotfiles"
  ignore_errors: true

- name: Add source my bashrc
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/.bashrc"
    state: present
    line: source $HOME/src/github.com/jiro4989/dotfiles/bash/bashrc

- name: Create empty zshrc
  file:
    path: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: touch

- name: Add source my zshrc
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: present
    line: source $HOME/src/github.com/jiro4989/dotfiles/zsh/zshrc

- name: Change shell to zsh
  become: true
  shell: "chsh -s /usr/bin/zsh"
