---

- name: Add source my bashrc
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/.bashrc"
    state: present
    line: source $HOME/src/github.com/jiro4989/dotfiles/bash/bashrc

- name: Add source my zshrc
  lineinfile:
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    state: present
    line: source $HOME/src/github.com/jiro4989/dotfiles/zsh/zshrc
