---

- name: Install apt packages
  become: true
  apt:
    name:
      - mysql-workbench
      - ruby
      - ibus-mozc
      - python3
      - python3-pip
      - zsh
      - git
      - systemd
      - snapd
      - docker.io
      - vim
      - vim-gnome
      - node
    update_cache: yes
    state: latest

