---

- name: Install snap packages
  become: true
  apt:
    name:
      - snapd
      - systemd
      - mysql-workbench
      - ibus-mozc
      - zsh
      - git
      - vim
      - vim-gnome
    update_cache: yes
    state: latest
