---

- name: Install snap packages
  become: true
  apt:
    name:
      - snapd
      - systemd
      - mysql-workbench
      - curl
      - guake
      - fcitx
      - fcitx-mozc
      - fcitx-config-common
      - ibus-mozc
      - zsh
      - git
      - vim
      - vim-gnome
      - nodejs
      - npm
      - ruby
      - gem
      - krita
      - kazam
      - steam
    update_cache: yes
    state: latest
