---

- name: Install snap packages
  become: true
  apt:
    name:
      - snapd
      - systemd
      - mysql-workbench
      - curl
      - guake
      - terminator
      - fcitx
      - fcitx-mozc
      - fcitx-config-common
      - ibus-mozc
      - zsh
      - git
      - vim
      - vim-gnome
      - nodejs
      - npm
      - python3
      - ruby
      - gem
      - krita
      - kazam
      - steam
      - tig
      - rxvt-unicode
      - i3
      - volumeicon-alsa
      - xclip
      - unar
    update_cache: yes
    state: latest
