---

- name: Install apt packages
  apt:
    name:
      - snapd
      - systemd
      - mysql-workbench
      - curl
      - fcitx
      - fcitx-mozc
      - fcitx-config-common
      - ibus-mozc
      - zsh
      - git
      - vim
      - vim-gnome
      - nodejs
      - npm
      - python3
      - python-pip
      - python3-pip
      - ruby
      - gem
      - krita
      - krita-l10n
      - kazam
      - steam
      - tig
      - i3
      - volumeicon-alsa
      - xclip
      - unar
      - fonts-ricty-diminished
      - screenfetch
      - chromium-browser
      - chromium-browser-l10n
      - g++
      - tmux
      - docker
      - docker.io
      - docker-compose
      - winehq-stable
      - guake
      - ffmpeg
      - openjdk-11-jdk
    update_cache: yes
    state: latest
