---

- name: Get fonts
  git:
    repo: "https://github.com/powerline/fonts"
    dest: /tmp/fonts

- name: Copy fonts
  become: true
  copy:
    src: /tmp/fonts/SourceCodePro
    dest: /usr/share/fonts/SourceCodePro
