---

- name: Get latest font file information
  uri:
    url: "https://api.github.com/repos/yuru7/HackGen/releases/latest"
    return_content: true
    body_format: json
  register: response

- name: Download font file and unarchive
  unarchive:
    src: "{{ response.json.assets[0].browser_download_url }}"
    dest: "/tmp"
    remote_src: yes

- name: Copy font files
  become: true
  copy:
    src: "{{ item }}"
    dest: "/usr/share/fonts/TTF/"
  with_fileglob:
    - "/tmp/HackGen_{{ hackgen_version }}/*.ttf"

- name: Update font cache
  shell: "fc-cache -f -v"
