---

- name: Download font file and unarchive
  unarchive:
    src: "https://github.com/yuru7/HackGen/releases/download/{{ hackgen_version }}/HackGen_{{ hackgen_version }}.zip"
    dest: "/tmp"
    remote_src: yes

- name: Copy font files
  become: true
  copy:
    src: "{{ item }}"
    dest: "/usr/share/fonts/TTF/"
  with_fileglob:
    - "/tmp/HackGen_{{ hackgen_version }}/*.ttf"

- name: Update font cache
  shell: "fc-cache -f -v"
