---

- name: Install snap packages
  become: true
  pacman:
    name:
      - snapd
      - systemd
        #- mysql-workbench
      - fcitx
      - fcitx-mozc
      - fcitx-configtool
      - zsh
      - git
      - vim
      - nodejs
      - npm
      - pulseaudio
      - pavucontrol
      - krita
      - steam
      - tig
      - glibc
      - nim
      - nimble
      - snapper
      - noto-fonts-emoji
      - noto-fonts-extra
        # ERROR: occured conflicting dependencies...
        #- gvim
    update_cache: yes
    state: latest
