---

- name: Install snap packages
  become: true
  pacman:
    name:
      - snapd
      - systemd
        #- mysql-workbench
      - fcitx
      - fcitx-mozc
      - fcitx-configtool
      - zsh
      - git
      - gvim
      - nodejs
      - npm
      - pulseaudio
      - pavucontrol
      - krita
      - steam
      - tig
      - glibc
      - snapper
      - noto-fonts-emoji
      - noto-fonts-extra
      - wine
      - code
      - ruby
      - docker
      - docker-compose
    update_cache: yes
    state: latest
