---

- name: Install yum packages
  become: true
  yum:
    name:
      - "https://centos7.iuscommunity.org/ius-release.rpm"
      #- mysql-workbench
      - ruby
      #- ibus-mozc
      - python36
      - python36-pip
      - zsh
      - git
      - systemd
      - snapd
      - docker
      - vim
    update_cache: yes
    state: present
