---

- name: Install dnf packages
  become: true
  dnf:
    name:
      - mysql-workbench
      - ruby
      - ibus-mozc
      - python3
      - python3-pip
      - zsh
      - git
      - systemd
      - snapd
      - docker.io
      - vim
      - vim-gnome
    update_cache: yes
    state: present
