---

- name: Make config directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory

- name: Starting snapd
  become: true
  systemd:
    name: snapd
    state: started

# TODO: if ansible version is over 2.8 then change module 'shell' to 'snap'.
- name: Install snap packages
  become: true
  shell: "snap install {{ item }} --classic"
  with_items:
    - conjure-up
    - minikube
    - vscode
    - chromium

# - name: Install snap packages
#   become: true
#   snap:
#     name:
#       - conjure-up
#       - minikube
#       - vscode
#       - chromium
#     classic: true

- name: Upgrade pip
  become: true
  ignore_errors: true
  pip:
    name:
      - pip
    executable: pip3
    state: latest

- name: Install pip modules
  become: true
  ignore_errors: true
  pip:
    name:
      - pynvim
      - python-language-server
    executable: pip3
    state: latest
