---

- name: Make config directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory
- name: Install apt packages
  become: true
  apt:
    name:
      - mysql-workbench
      - ruby
      - ibus-mozc
      - python3
      - python3-pip
      - zsh
      - git
      - systemd
    update_cache: yes
    state: present
- name: Upgrade pip
  become: true
  ignore_errors: true
  pip:
    name:
      - pip
    executable: pip3
    state: latest
- name: Install pip modules
  become: true
  ignore_errors: true
  pip:
    name:
      - pynvim
      - python-language-server
    executable: pip3
    state: latest
