---

- name: Make config directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory

- name: Install apt packages
  become: true
  apt:
    name:
      - mysql-workbench
      - ruby
      - ibus-mozc
      - python3
      - python3-pip
      - zsh
      - git
      - systemd
      - snapd
    update_cache: yes
    state: present

# TODO: if ansible version is over 2.8 then change module 'shell' to 'snap'.
- name: Install snap packages
  become: true
  shell: "snap install {{ item }} --classic"
  with_items:
    - conjure-up
    - minikube
    - vscode
    - chromium

# - name: Install snap packages
#   become: true
#   snap:
#     name:
#       - conjure-up
#       - minikube
#       - vscode
#       - chromium
#     classic: true

- name: Upgrade pip
  become: true
  ignore_errors: true
  pip:
    name:
      - pip
    executable: pip3
    state: latest

- name: Install pip modules
  become: true
  ignore_errors: true
  pip:
    name:
      - pynvim
      - python-language-server
    executable: pip3
    state: latest
