---

- name: Make config directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.config"
    state: directory

- name: Install minikube
  become: true
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: 0755
    owner: root
    group: root

- name: Starting snapd
  become: true
  systemd:
    name: snapd
    state: started

# TODO: if ansible version is over 2.8 then change module 'shell' to 'snap'.
- name: Install snap packages
  become: true
  shell: "snap install {{ item }} --classic"
  with_items:
    - conjure-up
    - vscode
    - chromium
    - ruby
    - python36

- name: Install apt packages
  become: true
  apt:
    name:
      - mysql-workbench
      - ibus-mozc
      - zsh
      - git
      - systemd
      - snapd
      - vim
      - vim-gnome
    update_cache: yes
    state: latest

# - name: Install snap packages
#   become: true
#   snap:
#     name:
#       - conjure-up
#       - minikube
#       - vscode
#       - chromium
#     classic: true

- name: Upgrade pip
  become: true
  ignore_errors: true
  pip:
    name:
      - pip
    executable: pip3
    state: latest

- name: Install pip modules
  become: true
  ignore_errors: true
  pip:
    name:
      - pynvim
      - python-language-server
    executable: pip3
    state: latest

- name: Mkdir lf src
  become: true
  file:
    path: /usr/local/src/lf/r10
    state: directory
    recurse: true
    mode: 0755
    owner: root
    group: root

- name: Install terminal filer
  become: true
  get_url:
    url: "https://github.com/gokcehan/lf/releases/download/r10/lf-linux-amd64.tar.gz"
    dest: /usr/local/src/lf/r10/lf-linux-amd64.tar.gz

- name: Unarchive lf
  become: true
  unarchive:
    src: /usr/local/src/lf/r10/lf-linux-amd64.tar.gz
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
